### ISSUE TITLE
WARNING: Параметры ключа не соответствуют алгоримам подписи ГОСТ и обмена Диффи-Хелмана

### ISSUE THREAD

**Issue by Insapov** [diadoc/diadocsdk-java#1]
Добрый день!
Я представляю компанию Никохим.
Пытаемся приконнектиться к диадоку, выдается сообщение:
22.06.2016 12:52:34 ru.CryptoPro.JCP.tools.Starter check
INFO: JCP loaded.
22.06.2016 12:52:34 ru.CryptoPro.Crypto.Key.KeyAgreement engineInit
WARNING: Параметры ключа не соответствуют алгоримам подписи ГОСТ и обмена Диффи-Хелмана
java.security.InvalidKeyException: Параметры ключа не соответствуют алгоримам подписи ГОСТ и обмена Диффи-Хелмана
at ru.CryptoPro.Crypto.Key.KeyAgreement.engineInit(Unknown Source)
at javax.crypto.KeyAgreement.a(DashoA13*..)
at javax.crypto.KeyAgreement.a(DashoA13*..)
at javax.crypto.KeyAgreement.init(DashoA13*..)
at javax.crypto.KeyAgreement.init(DashoA13*..)
at Diadoc.Api.DiadocApi.decryptToken(DiadocApi.java:263)
at Diadoc.Api.DiadocApi.getAuthToken(DiadocApi.java:214)
at Diadoc.Api.DiadocApi.Authenticate(DiadocApi.java:179)
at diaconn.Diaconn.main(Diaconn.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Exception in thread "main" java.security.InvalidKeyException: Параметры ключа не соответствуют алгоримам подписи ГОСТ и обмена Диффи-Хелмана
at ru.CryptoPro.Crypto.Key.KeyAgreement.engineInit(Unknown Source)
at javax.crypto.KeyAgreement.a(DashoA13*..)
at javax.crypto.KeyAgreement.a(DashoA13*..)
at javax.crypto.KeyAgreement.init(DashoA13*..)
at javax.crypto.KeyAgreement.init(DashoA13*..)
at Diadoc.Api.DiadocApi.decryptToken(DiadocApi.java:263)
at Diadoc.Api.DiadocApi.getAuthToken(DiadocApi.java:214)
at Diadoc.Api.DiadocApi.Authenticate(DiadocApi.java:179)
at diaconn.Diaconn.main(Diaconn.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Как нам победить эту проблему?
Текст программы : 
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diaconn;

import Diadoc.Api.*;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;
import java.security.cert.CertificateException;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;

/*
 * @author Zaikin
 */
public class Diaconn {

    /**
     * @param args the command line arguments
     */
    // URL веб-сервиса Диадок
    private static final String DefaultApiUrl = "https://diadoc-api.kontur.ru";
    // идентификатор клиента
    private static final String DefaultClientId = "nikohim2016-1bb2ef3f-b9f5-4240-81dc-1009dcf864f4";
    //
    private static final String DefaultPathToCert = "D:\\nikochem.c";

    public static void main(String[] args) throws KeyManagementException, NoSuchAlgorithmException, IOException, CertificateException, Exception {
        // TODO code application logic here
        DiadocApi api = new Diadoc.Api.DiadocApi(DefaultClientId, DefaultApiUrl);
        InputStream inStream = null;
        inStream = new FileInputStream(DefaultPathToCert);
        CertificateFactory cf = CertificateFactory.getInstance("X.509");
        X509Certificate cert = (X509Certificate) cf.generateCertificate(inStream);
        api.Authenticate(cert);

//System.out.println ("Hello World");
    }
}

 
Подключенные библиотеки во вложенном файле.
[lib.txt](https://github.com/diadoc/diadocsdk-java/files/346508/lib.txt)

[lib.txt](https://github.com/diadoc/diadocsdk-java/files/346522/lib.txt)

**Comment by asvyazin** [comment]
Такую ошибку выдает Crypto Pro JCP, если не может найти секретный ключ для сертификата, например для расшифровки чего-либо (как в данном случае), в своем хранилище.

Хранилища у Crypto Pro JCP и CSP - отличаются. По умолчанию JCP смотрит на диске в директории "C:\Users\<user>\AppData\Local\Crypto Pro" (в Unix - /var/opt/cprocsp/keys/<user>). 

Если секретный ключ находится на флешке, то в эту директорию нужно скопировать с флешки директорию с именем вида xxxx.000 целиком (в ней будет несколько файлов). Директории Crypto Pro на диске может не быть, в таком случае ее придется создать.

Если секретный ключ - в реестре, то его надо сначала выгрузить на флешку средствами Crypto Pro CSP, а оттуда скопировать на диск.

Настройки хранилища секретных ключей JCP можно до какой-то степени переопределить при помощи скрипта ControlPane.bat (ControlPane.sh), который есть в составе JCP. При запуске этому скрипту надо передать путь к директории JRE (в которую было установлено Crypto Pro JCP).

**Comment by Insapov** [comment]
Было проделано следующее: выгружен ключ  из реестра на флешку средствами Crypto Pro CSP, а оттуда скопирован на диск. С помощью скрипта переопрелена папка настройки хранилища. 
Теперь вот такая ошибка 
"C:\Program Files\Java\jdk1.6.0_45\bin\java" -Didea.launcher.port=7535 "-Didea.launcher.bin.path=C:\Program Files\JetBrains\IntelliJ IDEA 15.0.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.6.0_45\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\ASN1P.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\CAdES.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCP.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCPRequest.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCPRevCheck.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCPRevTools.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCPinst.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCPxml.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCryptoP.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\XMLDSigRI.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\asn1rt.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\forms_rt.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\jce.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\resources.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\rt.jar;D:\Users\zaikin\OneDrive\workspace\Java\DiaConn\out\production\DiaConn;D:\Users\zaikin\OneDrive\workspace\Java\Lib\commons-io-2.5.jar;D:\Users\zaikin\OneDrive\workspace\Java\Lib\commons-logging-1.0.3.jar;D:\Users\zaikin\OneDrive\workspace\Java\Lib\diadocsdk-1.36.2.jar;D:\Users\zaikin\OneDrive\workspace\Java\Lib\httpclient-java4-4.1.2.jar;D:\Users\zaikin\OneDrive\workspace\Java\Lib\httpcore-java4-4.1.2.jar;D:\Users\zaikin\OneDrive\workspace\Java\Lib\protobuf-java4-2.4.1.jar;C:\Program Files\JetBrains\IntelliJ IDEA 15.0.3\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain diaconn.Diaconn
06.07.2016 11:57:22 ru.CryptoPro.JCP.tools.Starter check
INFO: Loading JCP 1.0.54 36641
06.07.2016 11:57:23 ru.CryptoPro.JCP.tools.Starter check
INFO: JCP loaded.
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/codec/binary/Hex
 at Diadoc.Api.CertificateHelper.getThumbPrint(CertificateHelper.java:175)
 at Diadoc.Api.CertificateHelper.getPrivateKey(CertificateHelper.java:138)
 at Diadoc.Api.DiadocApi.decryptToken(DiadocApi.java:262)
 at Diadoc.Api.DiadocApi.getAuthToken(DiadocApi.java:214)
 at Diadoc.Api.DiadocApi.Authenticate(DiadocApi.java:179)
 at diaconn.Diaconn.main(Diaconn.java:43)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
 at java.lang.reflect.Method.invoke(Method.java:597)
 at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.binary.Hex
 at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
 at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
 ... 11 more

Process finished with exit code 1

Подскажите пожалуйста что не так, и  как нам победить эту ошибку?

**Comment by asvyazin** [comment]
Похоже не хватает ссылки на commons-codec

В classpath-е должно добавиться что-то вроде **commons-codec-1.6.jar**

**Comment by Insapov** [comment]
Теперь выдает ошибку:

"C:\Program Files\Java\jdk1.6.0_45\bin\java" -Didea.launcher.port=7534 "-Didea.launcher.bin.path=C:\Program Files\JetBrains\IntelliJ IDEA 15.0.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.6.0_45\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\ASN1P.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\CAdES.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCP.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCPRequest.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCPRevCheck.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCPRevTools.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCPinst.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCPxml.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCryptoP.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\XMLDSigRI.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\asn1rt.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\forms_rt.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\jce.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\resources.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\rt.jar;D:\Users\zaikin\OneDrive\workspace\Java\DiaConn\out\production\DiaConn;D:\Users\zaikin\OneDrive\workspace\Java\Lib\commons-io-2.5.jar;D:\Users\zaikin\OneDrive\workspace\Java\Lib\commons-logging-1.0.3.jar;D:\Users\zaikin\OneDrive\workspace\Java\Lib\diadocsdk-1.36.2.jar;D:\Users\zaikin\OneDrive\workspace\Java\Lib\httpclient-java4-4.1.2.jar;D:\Users\zaikin\OneDrive\workspace\Java\Lib\httpcore-java4-4.1.2.jar;D:\Users\zaikin\OneDrive\workspace\Java\Lib\protobuf-java4-2.4.1.jar;D:\Users\zaikin\Downloads\commons-codec-1.6.jar\commons-codec-1.6.jar;C:\Program Files\JetBrains\IntelliJ IDEA 15.0.3\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain diaconn.Diaconn
07.07.2016 15:14:24 ru.CryptoPro.JCP.tools.Starter check
INFO: Loading JCP 1.0.54 36641
07.07.2016 15:14:24 ru.CryptoPro.JCP.tools.Starter check
INFO: JCP loaded.
Exception in thread "main" java.lang.UnsupportedOperationException
 at javax.crypto.CipherSpi.engineGetKeySize(DashoA13*..)
 at javax.crypto.Cipher.b(DashoA13*..)
 at javax.crypto.Cipher.a(DashoA13*..)
 at javax.crypto.Cipher.a(DashoA13*..)
 at javax.crypto.Cipher.a(DashoA13*..)
 at javax.crypto.Cipher.init(DashoA13*..)
 at javax.crypto.Cipher.init(DashoA13*..)
 at Diadoc.Api.DiadocApi.gostUnwrapKey(DiadocApi.java:239)
 at Diadoc.Api.DiadocApi.decryptToken(DiadocApi.java:267)
 at Diadoc.Api.DiadocApi.getAuthToken(DiadocApi.java:214)
 at Diadoc.Api.DiadocApi.Authenticate(DiadocApi.java:179)
 at diaconn.Diaconn.main(Diaconn.java:43)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
 at java.lang.reflect.Method.invoke(Method.java:597)
 at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Process finished with exit code 1

**Comment by Insapov** [comment]
После прочтения https://support.cryptopro.ru/index.php?/Knowledgebase/Article/View/44/6/snjatie-ehksportnykh-ogrnichenijj
и замены файлов,
имеем ниже приведенную ошибку. 
Подскажите, пожалуйста,  как ее победить?

"C:\Program Files\Java\jdk1.6.0_45\bin\java" -Didea.launcher.port=7532 "-Didea.launcher.bin.path=C:\Program Files\JetBrains\IntelliJ IDEA 15.0.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.6.0_45\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\ASN1P.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\CAdES.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCP.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCPRequest.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCPRevCheck.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCPRevTools.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCPinst.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCPxml.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\JCryptoP.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\XMLDSigRI.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\asn1rt.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\forms_rt.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\jce.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\resources.jar;C:\Program Files\Java\jdk1.6.0_45\jre\lib\rt.jar;D:\Users\zaikin\OneDrive\workspace\Java\DiaConn\out\production\DiaConn;D:\Users\zaikin\OneDrive\workspace\Java\Lib\commons-io-2.5.jar;D:\Users\zaikin\OneDrive\workspace\Java\Lib\commons-logging-1.0.3.jar;D:\Users\zaikin\OneDrive\workspace\Java\Lib\diadocsdk-1.36.2.jar;D:\Users\zaikin\OneDrive\workspace\Java\Lib\httpclient-java4-4.1.2.jar;D:\Users\zaikin\OneDrive\workspace\Java\Lib\httpcore-java4-4.1.2.jar;D:\Users\zaikin\OneDrive\workspace\Java\Lib\protobuf-java4-2.4.1.jar;D:\Users\zaikin\OneDrive\workspace\Java\Lib\commons-codec-1.2.jar;C:\Program Files\JetBrains\IntelliJ IDEA 15.0.3\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain diaconn.Diaconn
07.07.2016 18:44:05 ru.CryptoPro.JCP.tools.Starter check
INFO: Loading JCP 1.0.54 36641
07.07.2016 18:44:05 ru.CryptoPro.JCP.tools.Starter check
INFO: JCP loaded.
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/codec/binary/StringUtils
 at Diadoc.Api.DiadocApi.getAuthToken(DiadocApi.java:215)
 at Diadoc.Api.DiadocApi.Authenticate(DiadocApi.java:179)
 at diaconn.Diaconn.main(Diaconn.java:43)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
 at java.lang.reflect.Method.invoke(Method.java:597)
 at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.binary.StringUtils
 at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
 at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
 ... 8 more

Process finished with exit code 1

**Comment by asvyazin** [comment]
Очень старые версии зависимостей. В common-codec-1.2 похоже еще нет такого класса. Он точно есть в версии 1.6, а последняя на текущий момент - 1.10

**Comment by Insapov** [comment]
Process finished with exit code 0
УРА!

**Comment by Insapov** [comment]
Process finished with exit code 0
УРА!

**Comment by asvyazin** [comment]
Вот и хорошо, закрываю тогда
