### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.String.isEmpty()Z

### ISSUE THREAD

**Issue by Insapov** [diadoc/diadocsdk-java#13]
Имеем следующую ошибку:
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.String.isEmpty()Z
 at Diadoc.Api.DiadocApi.getDiadocSdkVersion(DiadocApi.java:115)
 at Diadoc.Api.DiadocApi.getUserAgentString(DiadocApi.java:107)
 at Diadoc.Api.DiadocApi.createHttpClient(DiadocApi.java:99)
 at Diadoc.Api.DiadocApi.<init>(DiadocApi.java:92)
 at diaconn.Diaconn.main(Diaconn.java:38)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
 at java.lang.reflect.Method.invoke(Method.java:592)
 at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by asvyazin** [comment]
Метод String.isEmpty() появился только в версии Java 1.6, поправим

**Comment by Insapov** [comment]
Подскажите, когда примерно можно ожидать исправления?

**Comment by Insapov** [comment]
diadocsdk-1.36.2.jar  уже с исправлением?

**Comment by asvyazin** [comment]
Нет, новая версия пока не собрана, но исправления есть в master-е и будут выложены с очередным релизом.

**Comment by asvyazin** [comment]
Выложили версию 1.36.3 - с исправлением.
