### ISSUE TITLE
Java 6 update 211: SSLHandshakeException при авторизации

### ISSUE THREAD

**Issue by Sash0k** [diadoc/diadocsdk-java#166]
Добрый вечер.
После обновления Java 6 до последнего патча **Java 6 update 211** перестала работать авторизация.

Примерный код:
```java
String diadocUrl = "https://diadoc-api.kontur.ru";
Diadoc.Api.DiadocApi api = null;
try {
  api = new DiadocApi(clientID, diadocUrl);
} catch (Exception e) {
  throw new Exception("Ошибка инициализации DiadocApi: " + e.getLocalizedMessage());
}
// авторизация
try {
  api.Authenticate(login, password);
} catch (IOException e) {
  throw new Exception("Ошибка авторизации: " + e.getLocalizedMessage());
}
```
Ошибка:
```
Ошибка авторизации: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1323)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1350)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1334)
	at org.apache.http.conn.ssl.SSLSocketFactory.createLayeredSocket(SSLSocketFactory.java:552)
	at org.apache.http.conn.ssl.SSLSocketFactory.createLayeredSocket(SSLSocketFactory.java:433)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.updateSecureConnection(DefaultClientConnectionOperator.java:216)
	at org.apache.http.impl.conn.AbstractPoolEntry.layerProtocol(AbstractPoolEntry.java:243)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.layerProtocol(AbstractPooledConnAdapter.java:152)
	at org.apache.http.impl.client.DefaultRequestDirector.establishRoute(DefaultRequestDirector.java:814)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:615)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at Diadoc.Api.DiadocApi.ReceivePostHttpResponse(DiadocApi.java:394)
	at Diadoc.Api.DiadocApi.PerformPostHttpRequest(DiadocApi.java:414)
	at Diadoc.Api.DiadocApi.Authenticate(DiadocApi.java:191)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at com.sun.net.ssl.internal.ssl.InputRecord.read(InputRecord.java:462)
```

[Судя по логу](https://www.oracle.com/technetwork/java/javase/documentation/overview-156328.html#R160_211) в обновлении java убраны некоторые методы шифрования и сертификаты.
В DiadocApi TLS иницализируется [так](https://github.com/diadoc/diadocsdk-java/blob/7e233d836922c532f557a4c771d1169d8477fd3f/src/main/java/Diadoc/Api/DiadocApi.java#L174):
```java
    private static SSLSocketFactory getTrustfulSslSocketFactory() throws NoSuchAlgorithmException, KeyManagementException {
        SSLContext ctx = SSLContext.getInstance("TLS");
        X509TrustManager tm = new X509TrustManager() {
            public void checkClientTrusted(X509Certificate[] xcs, String string)
                    throws CertificateException {
            }

            public void checkServerTrusted(X509Certificate[] xcs, String string)
                    throws CertificateException {
            }

            public X509Certificate[] getAcceptedIssuers() {
                return null;
            }
        };
        ctx.init(null, new TrustManager[]{tm}, null);
        return new SSLSocketFactory(ctx, SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);
    }
```

Попытка пропатчить на 
```java
SSLContext ctx = SSLContext.getInstance("TLSv1.2");
```
для использования актуальной версии TLS результата не дала.
Подскажите, как решить проблему

**Comment by Sash0k** [comment]
проблему решили обновлением на Java 7.
в 6-й Java были доступны следующие алгоритмы шифрования:

> *	TLS_DHE_DSS_WITH_AES_128_CBC_SHA
> *	TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
> *	TLS_DHE_RSA_WITH_AES_128_CBC_SHA
> *	TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
> *	TLS_EMPTY_RENEGOTIATION_INFO_SCSV
> *	TLS_RSA_WITH_AES_128_CBC_SHA
> *	TLS_RSA_WITH_AES_128_CBC_SHA256

и их было недостаточно для handshake по TLSv1.2
