### ISSUE TITLE
Проблемы с отправкой УПД в формате 820

### ISSUE THREAD

**Issue by kirill-ivanov** [diadoc/diadocsdk-java#174]
При генерации и отправке документа УПД в новом формате 820 возникает непонятная ошибка:
```
org.apache.http.client.HttpResponseException: The server encountered an internal error or misconfiguration and was unable to complete your request
	at Diadoc.Api.DiadocApi.getResponseBytes(DiadocApi.java:467)
	at Diadoc.Api.DiadocApi.GenerateUniversalTransferDocumentXmlForSeller(DiadocApi.java:967)`
```

Код следующий:
```java
public void testSendUpd() {
        try {
            DiadocMessage_PostApiProtos.MessageToPost.Builder messBuilder = DiadocMessage_PostApiProtos.MessageToPost.newBuilder();
            messBuilder.setFromBoxId("a90c8ba0273a4a7bba994a92f5b9aa1c@diadoc.ru");
            messBuilder.setToBoxId("2d4b6b265b124fc19c065e76ab7a5ae6@diadoc.ru");
            messBuilder.setDelaySend(true);

            //Формируем УПД счет-фактура
            UniversalTransferDocumentInfoProtos.UniversalTransferDocumentSellerTitleInfo.Builder ufd = testGenerateUpd();

            //Генерируем файл
            GeneratedFile udfCF = connectApi.GenerateUniversalTransferDocumentXmlForSeller(ufd.build(), false, "utd820_05_01_01");

            DiadocMessage_PostApiProtos.XmlDocumentAttachment.Builder xmlAtt = DiadocMessage_PostApiProtos.XmlDocumentAttachment.newBuilder();

            DiadocMessage_PostApiProtos.SignedContent.Builder sgBuilder = DiadocMessage_PostApiProtos.SignedContent.newBuilder();
            sgBuilder.setContent(ByteString.copyFrom(udfCF.getContent()));

            xmlAtt.setSignedContent(sgBuilder.build());
            xmlAtt.setComment("СЧФДОП");

            //добавляем УПД в сообщение
            messBuilder.addUniversalTransferDocumentSellerTitles(xmlAtt.build());

            DiadocMessage_PostApiProtos.MessageToPost messageToPost = messBuilder.build();

            DiadocMessage_GetApiProtos.Message postedMessage = connectApi.PostMessage(messageToPost);
            String postedDraftId = postedMessage.getMessageId();
            System.out.println("postedDraftId = " + postedDraftId);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public UniversalTransferDocumentInfoProtos.UniversalTransferDocumentSellerTitleInfo.Builder testGenerateUpd() {
        UniversalTransferDocumentInfoProtos.UniversalTransferDocumentSellerTitleInfo.Builder upd = UniversalTransferDocumentInfoProtos.UniversalTransferDocumentSellerTitleInfo.newBuilder();
        upd.setFunction(UniversalTransferDocumentInfoProtos.FunctionType.InvoiceAndBasic);
        upd.setDocumentName("Счет-фактура и документ об отгрузке товаров (выполнении работ), передаче имущественных прав (документ об оказании услуг)");

        upd.setDocumentDate("01.01.2020");
        upd.setDocumentNumber("BILL_TEST_EDO");

        // СвПрод (Сведения о продавце)
        ExtendedOrganizationInfoProtos.ExtendedOrganizationInfo.Builder sellerBuilder = ExtendedOrganizationInfoProtos.ExtendedOrganizationInfo.newBuilder();
        sellerBuilder.setBoxId("");
        sellerBuilder.setOrgName("TEST");
        sellerBuilder.setInn("7709219099");
        sellerBuilder.setKpp("667843001");

        AddressProtos.Address.Builder adr = AddressProtos.Address.newBuilder();
        AddressProtos.ForeignAddress.Builder forAdr = AddressProtos.ForeignAddress.newBuilder();
        forAdr.setCountry("643");
        forAdr.setAddress("г. Москва");
        adr.setForeignAddress(forAdr.build());
        sellerBuilder.setAddress(adr.build());

        sellerBuilder.setOrgType(ExtendedOrganizationInfoProtos.OrgType.LegalEntity);
        upd.setSeller(sellerBuilder.build());

        //СвПокуп
        ExtendedOrganizationInfoProtos.ExtendedOrganizationInfo.Builder buyerBuilder = ExtendedOrganizationInfoProtos.ExtendedOrganizationInfo.newBuilder();
        buyerBuilder.setBoxId("2d4b6b265b124fc19c065e76ab7a5ae6@diadoc.ru");
        buyerBuilder.setInn("7713076301");
        buyerBuilder.setKpp("997750001");

        buyerBuilder.setAddress(adr.build());
        buyerBuilder.setOrgName("ООО Покупатель");
        buyerBuilder.setOrgType(ExtendedOrganizationInfoProtos.OrgType.LegalEntity);

        upd.setBuyer(buyerBuilder.build());
        upd.setCurrency("643");

        UniversalTransferDocumentInfoProtos.InvoiceTable.Builder invoiceTableBuilder = UniversalTransferDocumentInfoProtos.InvoiceTable.newBuilder();
        UniversalTransferDocumentInfoProtos.ExtendedInvoiceItem.Builder invoiceTableItemBuilder = UniversalTransferDocumentInfoProtos.ExtendedInvoiceItem.newBuilder();

        // СведТов (Сведения о товаре (работе, услуге))
        invoiceTableItemBuilder.setProduct("Услуга связи");
        invoiceTableItemBuilder.setUnitName("-");
        invoiceTableItemBuilder.setTaxRate(InvoiceInfoProtos.TaxRate.Percent_20);

        invoiceTableItemBuilder.setSubtotalWithVatExcluded("100.00");    //СтТовБезНДС
        invoiceTableItemBuilder.setVat("20.00");                         //СумНал
        invoiceTableItemBuilder.setSubtotal("120.00");                  //СтТовУчНал
        invoiceTableBuilder.addItems(invoiceTableItemBuilder.build());

        invoiceTableBuilder.setTotalWithVatExcluded("100.00");
        invoiceTableBuilder.setVat("20.00");
        invoiceTableBuilder.setTotal("120.00");


        upd.setInvoiceTable(invoiceTableBuilder.build());
        upd.setDocumentCreator("ООО Компания");

        ExtendedSignerProtos.ExtendedSigner.Builder signerBuilder = ExtendedSignerProtos.ExtendedSigner.newBuilder();
        ExtendedSignerProtos.ExtendedSignerDetails.Builder signerDetailBuilder = ExtendedSignerProtos.ExtendedSignerDetails.newBuilder();

        signerDetailBuilder.setSurname("Иванов И.И.");
        signerDetailBuilder.setSignerPowersBase("начальник");
        signerDetailBuilder.setFirstName(".");
        signerDetailBuilder.setSignerPowers(ExtendedSignerProtos.SignerPowers.InvoiceSigner);
        signerDetailBuilder.setSignerType(ExtendedSignerProtos.SignerType.LegalEntity);
        signerDetailBuilder.setSignerStatus(ExtendedSignerProtos.SignerStatus.AuthorizedPerson);
        signerDetailBuilder.setInn("7709219099");
        signerBuilder.setSignerDetails(signerDetailBuilder.build());
        upd.addSigners(signerBuilder.build());

        // Сведения о передаче (сдаче) // СвПер
        UniversalTransferDocumentInfoProtos.TransferInfo.Builder transferInfoBuilder = UniversalTransferDocumentInfoProtos.TransferInfo.newBuilder();
        transferInfoBuilder.setOperationInfo("Реализация");  // Содержание операции // СодОпер
        transferInfoBuilder.setTransferDate("01.01.2020");    // Дата отгрузки // ДатаПер
        transferInfoBuilder.addTransferBase(UniversalTransferDocumentInfoProtos.TransferBase.newBuilder().setBaseDocumentName("Договор").setBaseDocumentDate("01.01.2020").setBaseDocumentNumber("DOG_NUM_123").build());

        upd.setTransferInfo(transferInfoBuilder.build());

        return upd;
    }
```

Если в момент генерации файла не указывать формат, то документ сформируется и отправится корректно в старом формате:
```java
GeneratedFile udfCF = connectApi.GenerateUniversalTransferDocumentXmlForSeller(ufd.build(), false, "utd820_05_01_01");
```

**Comment by kirill-ivanov** [comment]
Если вместо
```java
GeneratedFile udfCF = connectApi.GenerateUniversalTransferDocumentXmlForSeller(ufd.build(), false, "utd820_05_01_01");
```
сформировать вот так
```java
GeneratedFile udfCF = connectApi.GenerateSenderTitleXml(boxIdFrom, "UniversalTransferDocument", "СЧФДОП", "utd820_05_01_01", ufd.build().toByteArray(), null, false);
```
получается ошибка
```
org.apache.http.client.HttpResponseException: Invalid data UserContractData:
', hexadecimal value 0x08, is an invalid character. Line 1, position 1.
	at Diadoc.Api.DiadocApi.getResponseBytes(DiadocApi.java:467)
	at Diadoc.Api.DiadocApi.GenerateSenderTitleXml(DiadocApi.java:1112)
```

**Comment by DMokhnatkin** [comment]
Метод ожидает на вход упрощенную xml вашего документа. https://api-docs.diadoc.ru/ru/latest/http/GenerateTitleXml.html. Вы же передаете бинарное представление protobuf класса. Вам нужно самостоятельно сформировать UserDataXml (в документации есть пример) и передавать его.

**Comment by kirill-ivanov** [comment]
Уточните, что значит "упрощенный xml документа"?
Подскажите ссылку с описанием формирования UserDataXml.

**Comment by NataliaShumikhina** [comment]
Упрощеный xml - это UserDataXml
Зачем он нужен (выдержка из документации):

> Титул — это xml-файл, соответствующий xsd-схеме. Часть данных в титуле может быть заполнена только пользователем — это информация о товарах, услугах и т.д. А часть данных может быть заполнена автоматически на основании формата и информации в Диадоке. Например, заполнить реквизиты организации продавца и покупателя по идентификатору ящика, установить значения КНД, версии формата, версии программы и т.д. Для упрощения генерации, Диадок позволяет заполнить только «пользовательский» xml-файл, он же UserDataXml. На базе UserDataXml метод генерации сформирует основной титул, дополнив его всеми необходимыми данными согласно xsd-схеме.

Подробнее можно посмотреть здесь https://api-docs.diadoc.ru/ru/latest/howto/utd820.html
Там есть подробное описание, откуда взять UserDataXml и как с ним можно работать
