### ISSUE TITLE
RuntimeException при получении печатной формы PrintFormClient.generatePrintForm

### ISSUE THREAD

**Issue by bovin-a** [diadoc/diadocsdk-java#175]
Коллеги, доброго времени суток. Подскажите, пожалуйста, почему может возникать такое исключение при вызове метода получения печатной формы?

    java.lang.RuntimeException: null
        at Diadoc.Api.auth.DiadocCredentials.getPassword(DiadocCredentials.java:56)
        at org.apache.http.impl.auth.BasicScheme.authenticate(BasicScheme.java:164)
        at org.apache.http.impl.auth.HttpAuthenticator.doAuth(HttpAuthenticator.java:239)
        at org.apache.http.impl.auth.HttpAuthenticator.generateAuthResponse(HttpAuthenticator.java:202)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:263)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at Diadoc.Api.httpClient.DiadocHttpClient.getRawResponse(DiadocHttpClient.java:111)
        at Diadoc.Api.print.PrintFormClient.generatePrintForm(PrintFormClient.java:49)

**Comment by DMokhnatkin** [comment]
Добрый день. Такая ошибка возникает если вы выполняете запрос без авторизации (или авторизация прошла неуспешно).

**Comment by bovin-a** [comment]
Спасибо!
