### ISSUE TITLE
eventsClient бросает NullPointerException

### ISSUE THREAD

**Issue by dk2k** [diadoc/diadocsdk-java#192]
Стек:
java.lang.NullPointerException
	at Diadoc.Api.httpClient.DiadocHttpClient.getResponseBytes(DiadocHttpClient.java:109)
	at Diadoc.Api.httpClient.DiadocHttpClient.performRequest(DiadocHttpClient.java:77)
	at Diadoc.Api.events.EventsClient.getLastEvent(EventsClient.java:53)

Ящик 7ba8a389185a48e088d15a72867a56ca@diadoc.ru
Используется java sdk diadocsdk-3.2.2.jar

**Comment by ThisIsBuddyRIch** [comment]
Ошибку исправил, можете обновляться. https://github.com/diadoc/diadocsdk-java/releases/tag/versions%2F3.2.3

**Comment by dk2k** [comment]
Спасибо!
