### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError: Bad version number in .class file

### ISSUE THREAD

**Issue by Insapov** [diadoc/diadocsdk-java#21]
Сообщение об ошибке:
Exception in thread "main" java.lang.UnsupportedClassVersionError: Bad version number in .class file
 at java.lang.ClassLoader.defineClass1(Native Method)
 at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
 at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
 at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
 at java.net.URLClassLoader.access$100(URLClassLoader.java:56)
 at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
 at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:268)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
 at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
 at Diadoc.Api.DiadocApi.GetResponseBytes(DiadocApi.java:314)
 at Diadoc.Api.DiadocApi.PerformPostHttpRequest(DiadocApi.java:319)
 at Diadoc.Api.DiadocApi.Authenticate(DiadocApi.java:178)
 at diaconn.Diaconn.main(Diaconn.java:44)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
 at java.lang.reflect.Method.invoke(Method.java:592)
 at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Подключено:
commons-codec-1.10.jar
commons-io-2.5.jar
commons-logging-1.0.3.jar
diadocsdk-1.36.3.jar
httpclient-java4-4.1.2.jar
httpcore-java4-4.1.2.jar
log4j-1.2.17.jar
protobuf-java-2.5.0.jar
jdk1.5.0_22

Подскажите, как победить ошибку.

**Comment by asvyazin** [comment]
Попробуйте собрать jar diadocsdk самостоятельно при помощи maven, используя свою версию JDK (1.5)

**Comment by Insapov** [comment]
Ошибка повторяется с новым  jar diadocsdk.

Используемые версии:
mvn  -v 
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 19:22:22+0400)
Maven home: D:\apache-maven-3.3.9\bin\..
Java version: 1.5.0_22, vendor: Sun Microsystems Inc.
Java home: C:\Program Files\Java\jdk1.5.0_22\jre
Default locale: ru_RU, platform encoding: Cp1251
OS name: "windows 7", version: "6.1", arch: "x86", family: "windows"

**Comment by Insapov** [comment]
Подбором библиотек эту ошибку удалось победить.

**Comment by asvyazin** [comment]
То есть это одна из зависимостей? А удалось понять, какая именно?

**Comment by Insapov** [comment]
Конкретно какая именно не исследовали. Заменили сразу большинство версий библиотек, воспользовавшись настройками из файла pom.xml из исходников diadoc-a.
