### ISSUE TITLE
java.lang.NoClassDefFoundError at javax.crypto.Cipher.getInstance(DashoA12275)

### ISSUE THREAD

**Issue by Insapov** [diadoc/diadocsdk-java#23]
Как победить следующую ошибку:

Exception in thread "main" java.lang.NoClassDefFoundError
	at javax.crypto.Cipher.getInstance(DashoA12275)
	at com.sun.net.ssl.internal.ssl.JsseJce.getCipher(JsseJce.java:90)
	at com.sun.net.ssl.internal.ssl.RSACipher.<init>(RSACipher.java:35)
	at com.sun.net.ssl.internal.ssl.RSACipher.getInstance(RSACipher.java:69)
	at com.sun.net.ssl.internal.ssl.PreMasterSecret.<init>(PreMasterSecret.java:82)
	at com.sun.net.ssl.internal.ssl.ClientHandshaker.serverHelloDone(ClientHandshaker.java:515)
	at com.sun.net.ssl.internal.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:160)
	at com.sun.net.ssl.internal.ssl.Handshaker.processLoop(Handshaker.java:495)
	at com.sun.net.ssl.internal.ssl.Handshaker.process_record(Handshaker.java:433)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:877)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1089)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1116)
	at com.sun.net.ssl.internal.ssl.SSLSocketImpl.getSession(SSLSocketImpl.java:1823)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:91)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:397)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:148)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:150)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:575)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:425)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
	at Diadoc.Api.DiadocApi.ReceivePostHttpResponse(DiadocApi.java:298)
	at Diadoc.Api.DiadocApi.PerformPostHttpRequest(DiadocApi.java:318)
	at Diadoc.Api.DiadocApi.Authenticate(DiadocApi.java:178)
	at diaconn.Diaconn.main(Diaconn.java:40)

**Comment by Insapov** [comment]
Подскажите в какую сторону копать с этой ошибкой?
Ява1.5 (jdk1.5.0_22),
файлы  local_policy US_export_policy заменены на скаченные с сайта IBM, 
jcp.1.0.54.

**Comment by asvyazin** [comment]
С сайта IBM? Или Oracle?

**Comment by Insapov** [comment]
C Oracle помогло
