### ISSUE TITLE
Получение информации о доверенности, GetPowerOfAttorneyInfo, эксепшен boxId не передан

### ISSUE THREAD

**Issue by nats56** [diadoc/diadocsdk-java#262]
При вызове метода получения информации о доверенности в версии 3.12.0, падает ошибка:
Caused by: org.apache.http.client.HttpResponseException: Could not get boxId from query param
	at Diadoc.Api.httpClient.DiadocHttpClient.getResponseBytes(DiadocHttpClient.java:113)
	at Diadoc.Api.httpClient.DiadocHttpClient.performRequest(DiadocHttpClient.java:83)
	at Diadoc.Api.powersOfAttorney.PowerOfAttorneyClient.getPowerOfAttorneyInfo(PowerOfAttorneyClient.java:122)

Что логично, т.к. в коде этот параметр в запрос не передается:
Diadoc.Api.powersOfAttorney.PowerOfAttorneyClient.getPowerOfAttorneyInfo(String, String, String):

 try {
            var request = RequestBuilder.get(
                            new URIBuilder(diadocHttpClient.getBaseUrl())
                                    .setPath("/GetPowerOfAttorneyInfo")
                                    .addParameter("messageId", messageId)
                                    .addParameter("entityId", entityId)
                                    .build());

            return PowerOfAttorneyInfo.parseFrom(diadocHttpClient.performRequest(request));
        } catch (URISyntaxException | IOException e) {
            throw new DiadocSdkException(e);
        }

**Comment by RusB** [comment]
Версия 3.14.0 потерялся параметр boxId в строке 118.
```
Diadoc.Api.exceptions.DiadocSdkException: org.apache.http.client.HttpResponseException: status code: 400, reason phrase: Could not get boxId from query param
	at Diadoc.Api.powersOfAttorney.PowerOfAttorneyClient.getPowerOfAttorneyInfo(PowerOfAttorneyClient.java:124)
```
