### ISSUE TITLE
регулярно получаем исключение при рабое с API.  java.lang.RuntimeException at Diadoc.Api.DiadocCredentials.getPassword(DiadocCredentials.java:54)

### ISSUE THREAD

**Issue by dsurogatov** [diadoc/diadocsdk-java#36]
Проблема состоит в следующем:
Делаем авторизацию:

`
X509Certificate currentCert = readCert();
diadocApi.Authenticate(currentCert);
`

Далее проверяем, что авторизавались:
`
diadocApi.IsAuthenticated() // возвращает true.`

Далее вызываем получение контрагентов:

`CounteragentProtos.CounteragentList contragents = diadocApi.GetCounteragents(org.getOrgId(), null, offsetKey);`

Тут у нас выбрасывает исключение:

`
java.lang.RuntimeException
        at Diadoc.Api.DiadocCredentials.getPassword(DiadocCredentials.java:54)
        at org.apache.http.impl.auth.BasicScheme.authenticate(BasicScheme.java:166)
        at org.apache.http.client.protocol.RequestAuthenticationBase.authenticate(RequestAuthenticationBase.java:120)
        at org.apache.http.client.protocol.RequestAuthenticationBase.process(RequestAuthenticationBase.java:83)
        at org.apache.http.client.protocol.RequestTargetAuthentication.process(RequestTargetAuthentication.java:81)
        at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:132)
        at org.apache.http.protocol.HttpRequestExecutor.preProcess(HttpRequestExecutor.java:166)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:486)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at Diadoc.Api.DiadocApi.ReceiveGetHttpResponse(DiadocApi.java:285)
        at Diadoc.Api.DiadocApi.PerformGetHttpRequest(DiadocApi.java:308)
        at Diadoc.Api.DiadocApi.GetCounteragents(DiadocApi.java:966)
        at mango.billing.diadoc.service.CounteragentsService.loadCounteragents(CounteragentsService.java:42)
`

В чем может быть проблема, какую диагностику можно провести?

**Comment by asvyazin** [comment]
Исходники DiadocApi не меняли?

**Comment by dsurogatov** [comment]
Добрый день, из последних изменений, перешли с 1.36.2 на 1.37.

На первый взгляд конфлита версии http клиента в cp нет.

diadocApi мы используем как singlton bean в Spring приложении.

На всякий случай даже обернули работу с API в блок synchronized.
